name: logehub
description: A Logistics Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  #sdk: "3.27.3"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  bdd_widget_test: ^1.2.1
  build_runner: ^2.4.9
  flutter_driver:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/listOfCompanies.jpg
    - assets/images/news.jpg
    - assets/images/events.jpg
    - assets/images/logo.jpg
    - assets/images/customer.jpg
    - assets/images/waybill.jpg
    - assets/images/trip.jpg
    - assets/images/tricolor.jpg
    - assets/images/material.jpg
    - assets/images/consignee.jpg
    - assets/images/invoice.jpg

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
